routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\EventBookController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\TransactionController;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//auth route for both

Route::group(['middleware' => ['auth']], function(){
    Route::get('/dashboard', 'App\Http\Controllers\DashboardController@index')->name
    ('dashboard');
});

//auth route for admin
Route::group([
    'middleware' => ['auth', 'role:admin'],
    'prefix' => 'dashboard',
    'as'     => 'dashboard.',
], function(){
    Route::get('content', 'App\Http\Controllers\DashboardController@content')->name('content');
    Route::post('content/store', 'App\Http\Controllers\DashboardController@storeContent')->name('store.content');
    Route::get('payment', 'App\Http\Controllers\DashboardController@payment')->name('payment');
    Route::get('addSlider', 'App\Http\Controllers\DashboardController@addSlider')->name('addSlider');
    Route::get('editSlider/{id}', 'App\Http\Controllers\DashboardController@editSlider')->name('editSlider');
    Route::put('updateSlider/{id}', 'App\Http\Controllers\DashboardController@updateSlider')->name('updateSlider');
    Route::post('content/{$id}', 'App\Http\Controllers\DashboardController@destroySlider')->name('destroySlider');

    Route::group(['prefix' => 'payment', 'as' => 'payment.'], function() {
        Route::get('/', [Admin\PaymentController::class, 'index'])->name('index');
        Route::get('/{id}', [Admin\PaymentController::class, 'show'])->name('show');
        Route::put('/{id}', [Admin\PaymentController::class, 'update'])->name('update');
    });
});

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::get('/dashboard/create/event', 'App\Http\Controllers\EventController@create')->name
    ('dashboard.create.event');

Route::post('/dashboard/store/event', 'App\Http\Controllers\EventController@store')->name
('dashboard.store.event');

Route::get('/dashboard/event', 'App\Http\Controllers\EventController@index')->name
('dashboard.event');

Route::get('/dashboard/eventDetail/{$id}', 'App\Http\Controllers\EventController@eventDetail')->name
('dashboard.eventDetail');

Route::get('events/{id}', [EventBookController::class, 'show'])->name('events.show');

Route::post('transaction/book', [TransactionController::class, 'book'])->name('transaction.book');
Route::get('transaction/{id}', [TransactionController::class, 'show'])->name('transaction.show');

Route::get('payment', [PaymentController::class, 'create'])->name('payment.create');
Route::post('payment', [PaymentController::class, 'store'])->name('payment.confirm');

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/add_event.blade.php
<x-app-layout>
    <div class="container mt-5">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>
                            Add New Event
                            <a href="{{ route('dashboard') }}" class="btn btn-outline-danger float-right">Back</a>
                            </h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('dashboard.store.event') }}" method="POST" enctype="multipart/form-data" class="was-validate">
                                @csrf
                                <div class="form-group">
                                    <label for="">Event Title</label>
                                    <input type="text" name="title" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="name" class="col-md-4 col-form-label">Event Category</label>
                                    <div class="col-md-6">
                                        <select name="category" id="province" class="form-control" required>
                                            <option value="">Select Event Category</option>
                                            @foreach ($eventCategory as $item => $category)
                                                <option value="{{ $category }}">{{ $category }}</option>
                                            @endforeach
                                        </select>
                                        <div class="valid-feedback">Valid.</div>
                                        <div class="invalid-feedback">Please fill out this field.</div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="">Event Organizer</label>
                                    <input type="text" name="event_organizer" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Location</label>
                                    <div class="col-md-6 mb-3">
                                        <select name="event_type" id="event_type" class="form-control" required>
                                            <option value="Offline">Offline</option>
                                            <option value="Online">Online</option>
                                        </select>
                                        <div class="valid-feedback">Valid.</div>
                                        <div class="invalid-feedback">Please fill out this field.</div>
                                    </div>
                                    <label class="ml-2" for="">Input with Location when the Event is Offline, and Input with Link when the Event is Online</label>
                                    <input type="text" name="location" class="form-control ml-2" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>
                                <div class="form-group">
                                    <label for="">Start Time</label>
                                    <input type="text" id="datepicker_start" name="start_time" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>
                                <div class="form-group">
                                    <label for="">End Time</label>
                                    <input type="text" id="datepicker_end" name="end_time" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Event Image Upload</label>
                                    <input type="file" name="image" class="form-control mb-1" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Event Summary</label>
                                    <input type="text" name="event_summ" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Event Description</label>
                                    <input type="text" name="event_desc" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Capacity</label>
                                    <input type="text" name="capacity" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <div class="form-group">
                                    <label for="">Price</label>
                                    <input type="text" name="price" class="form-control" required>
                                    <div class="valid-feedback">Valid.</div>
                                    <div class="invalid-feedback">Please fill out this field.</div>
                                </div>

                                <input type="hidden" value="hide" name="status" >

                                <div class="form-group">
                                    <button type="submit" class="btn btn-outline-dark float-right">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    @push('scripts')
        <script>
            $(document).ready(function () {
                $("#datepicker_start").daterangepicker();
                $("#datepicker_end").daterangepicker();
            })
        </script>
    @endpush
</x-app-layout>

resources/views/admindashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You Are admin!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/card_detail.blade.php
<x-app-layout>
    <div class="container mt-5">
        <div class="row">
            {{-- @foreach ($event as $eventitem)
            <div class="col-lg-4 col-md-6 col-sm-6 col-12">
              <div class="col">
                <div class="card h-100">
                  <a href="{{url('dashboard/eventDetail/'.$eventitem->id) }}">
                    <img src="{{asset('uploads/event/'.$eventitem->image) }}" class="card-img-top center" style="width: 415px; height:300px;" alt="Event Image">
                  </a>
                  <div class="card-body">
                    <h5 class="card-title">{{$eventitem->title}}</h5>
                    <p class="card-text">{{$eventitem->event_summ}}</p>
                    <div style="float: right;">
                      <small class="text-bold">Ticket Available <span class="badge bg-primary">{{$eventitem->capacity}}</span></small>
                    </div>
                    <br>
                    <div style="float: right; ">
                      <small class="text-bold">Ticket Price <span class="badge bg-success">{{$eventitem->price}}</span></small>
                    </div>
                  </div>
                  <div class="card-footer">
                      <div class="row">
                          <button class="btn btn-outline-dark">Buy Ticket</button>
                      </div>
                  </div>
                </div>
              </div>
            </div>
            @endforeach --}}
            it works
          </div>
    </div>
</x-app-layout>

resources/views/content.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-12">
                    @if (session('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                         <strong>Success!</strong> Content for Slider Added Successfully.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    @endif
                    <div class="card">
                        <div class="card-header">
                            <h4>
                            Content Slider
                            <a href="{{ route('dashboard.addSlider') }}" class="btn btn-outline-dark float-right">Add Slider</a>
                            </h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Heading</th>
                                        <th>Image</th>
                                        <th>Status</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @php
                                    $no =1;
                                    @endphp

                                    @foreach ($slider as $item => $value)
                                    <tr>
                                        <td>{{$no++}}</td>
                                        <td>{{$value -> heading}}</td>
                                        <td>
                                            <img src="{{ asset('uploads/slider/'.$value->image) }}" width="100px" alt="Slider Image">
                                        </td>
                                        <td>
                                            @if($value -> status == '1')
                                            Hidden
                                            @else 
                                            Visible
                                            @endif
                                        </td>
                                        <td>
                                        <a href=" {{ url('dashboard/editSlider/'.$value->id) }}" class="btn btn-outline-warning float-center">Edit</a> 
                                        </td>
                                        <td>
                                            {{-- <a href="{{ url('dashboard/content/'.$value->id) }}" class="btn btn-outline-danger float-center">Delete</a>  --}}
                                            <form action="{{ route('dashboard.destroySlider',$value->id) }}" method="POST">
                                                @csrf
                                                <input type="hidden" name="_method" value="DELETE">
                                                <button class="btn btn-outline-danger" type="submit">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</x-app-layout>

resources/views/edit_slider.blade.php
<x-app-layout>
    <div class="container mt-5">
            <div class="row">
                <div class="col-md-12">

                @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                     <strong>Success!</strong> Content for Slider Added Successfully.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                @endif
                    <div class="card">
                        <div class="card-header">
                            <h4>
                            Add New Content Slider
                            <a href="{{ route('dashboard.content') }}" class="btn btn-outline-danger float-right">Back</a>
                            </h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ url('dashboard/updateSlider/'.$slider->id) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                <div class="form-group">
                                    <label for="">Heading</label>
                                    <input type="text" name="heading" value="{{$slider->heading}}" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="">Description</label>
                                    <input type="text" name="description" value="{{$slider->description}}" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="">Link</label>
                                    <input type="text" name="link" value="{{$slider->link}}" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="">Link Name</label>
                                    <input type="text" name="link_name" value="{{$slider->link_name}}" class="form-control">
                                </div>

                                <div class="form-group">
                                    <label for="">Slider Image Upload</label>
                                    <input type="file" name="image"  value class="form-control mb-1">
                                    <img src="{{ asset('uploads/slider/'.$slider->image) }}" width="100px" alt="Slider Image">    
                                </div>

                                <div class="form-group">
                                    <label for="">Status</label>
                                    <input type="checkbox" name="status" {{$slider->status == '1' ? 'checked':''}}>
                                    <br>
                                    Check = Hidden
                                    <br>
                                    Uncheck = Visible
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-outline-dark float-right">Save</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</x-app-layout>

resources/views/event-detail.blade.php
<x-app-layout>
    <div class="container pt-4 pb-3">
        <div class="card">
            <div class="card-body p-0">
                <!-- Event Detail Header -->
                <div class="max-h-[360px]">
                    <div class="row border-b">
                        <div class="col-12 col-md-8 max-h-[360px] mw-100">
                            <img src="{{ asset('uploads/event/' . $event->image) }}" alt="{{ $event->title }}"
                                 class="mh-100 w-100">
                        </div>
                        <div class="col-12 col-md-4 px-3 py-4 max-h-[360px]">
                            <div class="position-relative w-100 h-100">
                                <span class="fw-light text-sm">{{ $event->start_time->format('M d') }}</span>
                                <h1 class="mt-5 fs-5 fw-bold">{{ $event->title }}</h1>
                                <p class="fw-light text-sm">by <span class="text-info font-normal">{{ $event->event_organizer }}</span></p>
                                <div class="w-full position-absolute bottom-0 pe-3">
                                    <p class="font-normal mb-1">{{ rupiah($event->price) }}</p>
                                    <div class="d-grid gap-2">
                                        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#eventBookModal">
                                            Tickets
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row px-3 pt-8 pb-4">
                    <div class="col-12 col-md-8 mt-3">
                        <div class="mx-md-5">
                            <p class="mb-5">{{ $event->event_summ }}</p>
                            <h3 class="fs-5 fw-bold mb-3">About this event</h3>
                            {!! $event->event_desc !!}
                        </div>
                    </div>
                    <div class="col-12 col-md-4">
                        <div class="mb-5 mt-3">
                            <h3 class="fs-5">Date and time</h3>
                            <div class="fw-light">
                                <p class="mb-0">{{ $event->start_time->format('D, M d, Y, h:i A') }} -</p>
                                <p class="mb-0">{{ $event->end_time->format('D, M d, Y, h:i A T') }}</p>
                            </div>
                        </div>
                        <div class="mb-3">
                            <h3 class="fs-5">Location</h3>
                            <div class="font-semibold">
                                <p>{{ $event->event_type === 'Online' ? 'Online Event' : $event->location }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('event-book-modal')

    @push('scripts')
        <script>
            const transactionForm = $('#transactionForm')

            $(document).ready(function () {
                $('#selectTicketQuantity').change(function () {
                    $('#totalPrice').text(rupiah(parseInt(this.value) * parseInt('{{ $event->price }}')))
                    $('#btnSubmitCheckout').prop('disabled', this.value == 0)

                    transactionForm.find('[name="qty"]').val(this.value)
                })

                $('#btnSubmitCheckout').click(() => transactionForm.submit())
            })

            function rupiah(number) {
                return new Intl.NumberFormat('id-ID', {
                    style: 'currency',
                    currency: 'IDR',
                    trailingZeroDisplay: 'stripIfInteger'
                }).format(number).replace(/(\.|,)00$/g, '')
            }
        </script>
    @endpush
</x-app-layout>

resources/views/event.blade.php
<x-app-layout>
    <div class="container p-5 my-5 border">
        <div class="row">
            <div class="col-md-12">
                @if (session('status'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                     <strong>Success!</strong> Content for Slider Added Successfully.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                @endif
                <div class="card">
                    <div class="card-header">
                         <h4>
                            Event List
                        <a href="{{ route('dashboard.create.event') }}" class="btn btn-outline-dark float-right">Add New Event</a>
                        </h4>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Title</th>
                                        <th>Image</th>
                                        <th>Description</th>
                                        <th>Status</th>
                                        <th>Show</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($event as $item => $value)
                                    <tr>
                                    <td>{{$value -> id}}</td>
                                        <td>{{$value -> title}}</td>
                                        <td>
                                            <img src="{{ asset('uploads/event/'.$value->image) }}" width="100px" alt="Slider Image">
                                        </td>
                                        <td>{{$value -> event_summ}}</td>
                                        <td>{{$value -> status}}</td>
                                        <td>
                                            <a href=" {{ url('dashboard/event/detail/'.$value->id) }}" class="btn btn-outline-success float-center">Show</a> 
                                        </td>
                                        <td>
                                            <a href=" {{ url('dashboard/event/edit/'.$value->id) }}" class="btn btn-outline-warning float-center">Edit</a> 
                                        </td>
                                        <td>
                                            <a href=" {{ url('dashboard/event/edit/'.$value->id) }}" class="btn btn-outline-danger float-center">Delete</a> 
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/userdashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You Are User!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/view_event.blade.php
<x-app-layout>
    <div class="container ">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-shadow">
                    <div class="card-head">
                        <div class="float-right">
                            <button>Edit</button>
                            <button>Delete</button>
                        </div>
                    </div>
                    <div class="card-body">
                        <h4 style="text-align: center">
                            {{$event->title}}
                        </h4>

                    </div>


                </div>
                
            </div>
    </div>
</x-app-layout>